demo/authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'auth'
urlpatterns = [
    path('register/', views.register_page, name="reg"),
    path('login/', views.login_page, name='login'),
    path('reset_password/', view=auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html'), name='reset_password'),
    path('logout/', views.logout_page, name='logout'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('profile<int:pk>/', views.profile_page, name='profile'),
]

demo/polls/urls.py
from django.urls import path
from . import views
#limit class views
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

app_name = 'polls'
urlpatterns = [
    path('', view=views.IndexView.as_view(), name='index'),
    path('polls/new/', view=views.create_question_choices, name='new'),
    path('polls/update/<int:pk>/', view=views.update_question_choices, name="update"),
    path('choices/add/<int:pk>/', view=views.add_question, name='add_choice'),
    path('polls/delete/<int:pk>/', view=login_required(views.DeleteQuestion.as_view(), login_url=reverse_lazy('auth:login')), name='delete'),
    path('details/<int:pk>/', view=login_required(views.DetailView.as_view(), login_url=reverse_lazy('auth:login')), name='detail'),
    path('polls/<int:pk>/results/', view=login_required(views.ResultsView.as_view(), login_url=reverse_lazy('auth:login')), name='results'),
    path('polls/<int:question_id>/vote/', view=views.vote, name='vote'),
    path('search/', view=views.question_search, name='search'),
]

demo/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('reset/<uidb64>/<token>/', view=auth_views.PasswordResetConfirmView.as_view(template_name='authentication/reset_password_done.html'), name='password_reset_confirm'),
    path('reset_password_sent/', view=auth_views.PasswordResetDoneView.as_view(template_name='authentication/reset_password_sent.html'), name='password_reset_done'),
    path('reset_password_complete/', view=auth_views.PasswordResetCompleteView.as_view(template_name='authentication/reset_password_complete.html'), name='password_reset_complete'),
    path('auth/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    question_text = models.CharField(max_length=255)
    update_date = models.DateTimeField('date last updated', auto_now=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    def __str__(self):
        return self.question_text
    # check if pulished recently
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

demo/polls/forms.py
from django.forms import ModelForm, Form, CharField
from .models import Question, Choice

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']

class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

class SarchForm(Form):
    query = CharField()

demo/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from .models import Question, Choice
from django.utils import timezone
from .forms import ChoiceForm, QuestionForm, SarchForm
#limiting user view for users not logged in
from django.contrib.auth.decorators import login_required
from django.forms.models import inlineformset_factory
from django.utils.decorators import method_decorator
from authentication.decorators import allowed_users
# search vector for search
from django.contrib.postgres.search import SearchVector
# pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# search
def question_search(request):
    form = SarchForm()
    query = None
    results = []
    paginator = Paginator(results, 10)
    page = request.GET.get('page') or 1
    if 'query' in request.GET:
        form = SarchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('question_text', 'pub_date', 'author__username')
            results = Question.objects.annotate(search=search_vector).filter(search=query)
            paginator = Paginator(results, 10)
            page = request.GET.get('page') or 1
            try:
                results = paginator.page(page)
            except PageNotAnInteger:
                results = paginator.page(1)
            except EmptyPage:
                results = paginator.page(paginator.num_pages)
    return render(request, 'polls/search.html', {'page':page, 'form': form, 'query': query, 'results': results})

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'questions_list'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
#create question view

@method_decorator(allowed_users(allowed_roles=['customer']), name='dispatch')
class CreateQuestion(generic.CreateView):
    model = Question
    fields = ['question_text']
    template_name = 'polls/new_question.html'
    def form_valid(self, form):
        form.instance.pub_date = timezone.now()
        form.instance.author = self.request.user
        self.question = form.save()
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('polls:detail', args=(self.question.id,))
# update view
class UpdateQuestion(generic.UpdateView):
    model = Question
    fields = ['question_text']
    template_name = 'polls/new_question.html'
    def get_success_url(self):
        return reverse('polls:detail', args=(self.object.id,))

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
# delete view
class DeleteQuestion(generic.DeleteView):
    model = Question
    template_name = 'polls/delete_question.html'
    def get_success_url(self):
        return reverse('polls:index')
# create question with choices
@login_required(login_url=reverse_lazy('auth:login'))
@allowed_users(allowed_roles=['customer'])
def create_question_choices(request):
    choice_formset = inlineformset_factory(Question, Choice, fields=['choice_text'], extra=4)
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question = question_form.save(commit=False)
            question.pub_date = timezone.now()
            question.author = request.user
            question.save()
            formset = choice_formset(request.POST, instance=question)
            if formset.is_valid():
                formset.save()
                return redirect('polls:detail', pk=question.pk)
    else:
        question_form = QuestionForm()
        formset = choice_formset()
    return render(request, 'polls/question_choices.html',{
        'question_form': question_form,
        'formset': formset
    })
@login_required(login_url=reverse_lazy('auth:login'))
@allowed_users(allowed_roles=['customer'])
def update_question_choices(request, pk):
    question = get_object_or_404(Question, pk=pk)
    choice_formset = inlineformset_factory(Question, Choice, fields=['choice_text'], extra=2)
    if request.method == "POST":
        question_form = QuestionForm(request.POST, instance=question)
        question_form.save()
        formset = choice_formset(request.POST, instance=question)
        if question_form.is_valid() and formset.is_valid():
            formset.save()
            return redirect('polls:detail', pk=question.pk)
    else:
        question_form = QuestionForm(instance=question)
        formset = choice_formset(instance=question)
    return render(request, 'polls/question_choices.html',{
        'question_form': question_form,
        'formset': formset
    })
# function to add choice to question
@login_required(login_url=reverse_lazy('auth:login'))
def add_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        form = ChoiceForm(request.POST)
        if form.is_valid():
            choice = form.save(commit=False)
            choice.question = question
            choice.save()
    return redirect('polls:detail', pk=question.pk)


# function view to vote without the actual view
@login_required(login_url=reverse_lazy('auth:login'))
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

demo/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}Polls{% endblock %}</title>
    <style type="text/css">

    </style>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    {% include 'polls/nav.html' %}
    <div class="container">
        {% block Body %}{% endblock %}
    </div>

    <script src="{% static 'js/bootstrap.bundle.js' %}" type="text/javascript"></script>
</body>
</html>

demo/polls/templates/polls/delete_question.html
{% extends 'polls/base.html' %}
{% block Title %}{{ question.question_text }}{% endblock %}
{% block Body %}
    <form action="" method="post" >
        {% csrf_token %}
        <fieldset>
            <legend>Are you sure?</legend>
            <p>Are you sure you want to delete poll: {{ question.question_text }}</p>
            <input type="submit" value="Delete">
            <input type="button" onclick="location.href='{% url 'polls:detail' question.id %}'" value="Cancel">
        </fieldset>
    </form>
{% endblock %}

demo/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block Title %}{{ question.question_text }} Detail{% endblock %}
{% block Body %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {%  if error_message %}
            <p style="color: red"><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <label for="choice{{ forloop.counter }}">
                <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
                {{ choice.choice_text }}
            </label>
            </br>
        {% endfor %}
        <input type="submit" value="Vote">
    </fieldset>
</form>
    {% if question.author == request.user %}
        <button type="button" onclick="location.href='{% url 'polls:update' question.id %}'">Update Question</button>
    {% endif %}
<a href="{% url 'polls:results' question.id %}">See Results</a>
    <form action="{% url 'polls:add_choice' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h2>Add Choice</h2></legend>
            <label for="choice_text">Choice:</label>
            <input type="text" name="choice_text" id="choice_text" placeholder="new choice">
            <input type="submit" value="Add Choice">
        </fieldset>
    </form>
{% endblock %}

demo/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block Title %}Questions List{% endblock %}
{% block Body %}
{% if questions_list %}
  <ul>
    {% for question in questions_list %}
      <li>
        <a href="{% url 'polls:detail' question.id %}">
          {{ question.question_text }}
        </a>
          {% if question.author == request.user %}
            <a href="{% url 'polls:update' question.id %}" type="button" class="btn btn-warning btn-sm">
                Update
            </a>
              <a href="{% url 'polls:delete' question.id %}" type="button" class="btn btn-danger btn-sm">
                  Delete
              </a>
          {% endif %}
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No polls avaliable.</p>
{% endif %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'polls:new' %}"  type="button" class="btn btn-primary">Add New Poll</a>
    {% endif %}
{% endblock %}

demo/polls/templates/polls/nav.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container container-fluid">
    <a class="navbar-brand" href="#">Polls App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:index' %}" aria-current="page">Home</a>
        </li>
        {% if request.user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:users' %}">Users</a>
            </li>
        {% endif %}
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:new' %}">New Poll</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:profile' request.user.profile.id %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:logout' %}">Log Out</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:login' %}">Log In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:reg' %}">Register</a>
            </li>
        {% endif %}
          <form class="d-flex" action="{% url 'polls:search' %}" method="get">
            <input type="text" class="form-control me-2" name="query" placeholder="search" value="{{ query }}" />
            <input type="submit" class="btn btn-outline-success" value="Search" />
        </form>
      </ul>
    </div>
  </div>
</nav>

demo/polls/templates/polls/new_question.html

{% extends 'polls/base.html' %}
{% block Title %}Question{% endblock %}
{% block Body %}
    <form action="" method="post" >
        {% csrf_token %}
        <fieldset>
            <legend>Poll</legend>
            {{ form|as_p }}
            <input type="submit" class="btn btn-success" value="Submit Poll">
        </fieldset>
    </form>
{% endblock %}

demo/polls/templates/polls/pagination.html
<div class="pagination">
     <span class="step-links">
       {% if page.has_previous %}
         <a href="?page={{ page.previous_page_number }}&query={{ query }}">Previous</a>
       {% endif %}
       <span class="current">
         Page {{ page.number }} of {{ page.paginator.num_pages }}.
       </span>
       {% if page.has_next %}
         <a href="?page={{ page.next_page_number }}&query={{ query }}">Next</a>
       {% endif %}
     </span>
</div>

demo/polls/templates/polls/question_choices.html
{% extends 'polls/base.html' %}
{% block Title %}Question{% endblock %}
{% block Body %}
    <form action="" method="post" >
        {% csrf_token %}
        <fieldset>
            <legend>Poll</legend>
            {{ question_form.as_p }}
            {{ formset.as_p }}
            <input type="submit" value="Submit Poll">
        </fieldset>
    </form>
{% endblock %}

demo/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block Title %}{{ question.question_text }}{% endblock %}
{% block Body %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }}{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote Again!</a>
<br>
<a href="{% url 'polls:index' %}">Back to Polls</a>
{% endblock %}

demo/polls/templates/polls/search.html
{% extends 'polls/base.html' %}
{% block title %}Sarch Polls{% endblock %}
{% block Body %}
    <h1>Search Polls</h1>
    <form class="d-flex" action="{% url 'polls:search' %}" method="get">
        <input type="text" class="form-control me-2" name="query" placeholder="search" value="{{ query }}" />
        <input type="submit" class="btn btn-outline-success" value="Search" />
    </form>

    {% if query %}
        <h2>Search Results for '{{ query }}'</h2>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {%  include 'polls/pagination.html' with page=results query=query %}
        {% for poll in results %}
            <h4><a href="{% url 'polls:detail' poll.id %}">{{ poll.question_text }}</a></h4>
        {% empty %}
            <p>No polls found matching '{{ query }}'</p>
        {% endfor %}
        {%  include 'polls/pagination.html' with page=results %}
{#        <p><a href="{% url 'polls:search' %}">Search Again</a></p>#}
    {% endif %}

{% endblock %}