demo/authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'auth'
urlpatterns = [
    path('register/', views.register_page, name="reg"),
    path('login/', views.login_page, name='login'),
    path('reset_password/', view=auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html'), name='reset_password'),
    path('logout/', views.logout_page, name='logout'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('profile<int:pk>/', views.profile_page, name='profile'),
]

demo/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('reset/<uidb64>/<token>/', view=auth_views.PasswordResetConfirmView.as_view(template_name='authentication/reset_password_done.html'), name='password_reset_confirm'),
    path('reset_password_sent/', view=auth_views.PasswordResetDoneView.as_view(template_name='authentication/reset_password_sent.html'), name='password_reset_done'),
    path('reset_password_complete/', view=auth_views.PasswordResetCompleteView.as_view(template_name='authentication/reset_password_complete.html'), name='password_reset_complete'),
    path('auth/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    picture = models.ImageField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    def get_absolute_url(self):
        return reverse('auth:profile', args=(self.pk,))

demo/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

demo/authentication/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user, allowed_users, staff_only
from django.contrib.auth.models import User, Group
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Profile

#profile page
@login_required(login_url='auth:login')
# @allowed_users(allowed_roles=['customer', 'admin'])
def profile_page(request, pk):
    return render(request, 'authentication/profile.html', context={
        'profile': Profile.objects.get(pk=pk),
    })

# Create your views here.
decorators = [login_required(login_url='auth:login'), staff_only]
@method_decorator(staff_only, name='dispatch')
class UsersView(generic.ListView):
    template_name = 'authentication/users.html'
    context_object_name = 'user_list'
    def get_queryset(self):
        return Profile.objects.all()

@unauthenticated_user
def register_page(request):
    if not Group.objects.filter(name='customer').exists():
        Group.objects.create(name='customer')
        Group.objects.create(name='admin')
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Account was created for ' + form.cleaned_data.get('username'))
            return redirect('auth:login')
        else:
            messages.error(request, 'Got a registration error: ' + str(form.error_messages))
    else:
        form = CreateUserForm()
    context = {'form': form}
    return render(request, 'authentication/reg.html', context)

@unauthenticated_user
def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('polls:index')
        else:
            messages.warning(request, 'Username or Password is incorrect')
    return render(request, 'authentication/login.html')

def logout_page(request):
    logout(request)
    return redirect('auth:login')

demo/authentication/templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}Authentication{% endblock %}</title>
    <style type="text/css">

    </style>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    {% include 'authentication/nav.html' %}
    <div class="container">
        {% block Body %}{% endblock %}
    </div>
    <script src="{% static 'js/bootstrap.bundle.js' %}" type="text/javascript"></script>
</body>
</html>

demo/authentication/templates/authentication/login.html
{%  extends 'authentication/base.html' %}
{% block Title %}Log-in{% endblock %}
{% block Body %}
    <form method="post" action="">
        <fieldset>
            <legend>Log-In</legend>
            {% csrf_token %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
            <input type="submit" value="LogIn">
        </fieldset>
    </form>
{% endblock %}

demo/authentication/templates/authentication/nav.html
<nav>
    <a href="{% url 'auth:login' %}" >Log in</a>
    <a href="{%  url 'auth:reset_password' %}">Forgot Password</a>
    <a href="{% url 'auth:reg' %}">Register</a>
</nav>

demo/authentication/templates/authentication/password_reset.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset{% endblock %}
{% block Body %}
    <form method="post">
        <fieldset>
            <legend>Password Reset</legend>
            <span>Enter your email address and we'll send you a link to reset your password.</span>
            <br>
            {% csrf_token %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <label for="email">Email</label>
            <input type="email" name="email" id="email">
        </fieldset>
            <input type="submit" class="btn btn-primary" value="Reset my Password">
    </form>
{% endblock %}

demo/authentication/templates/authentication/profile.html
{% extends 'polls/base.html' %}
{% block Title %}User Profile{% endblock %}
{% block Body %}
    <strong>User Name:</strong>{{ profile.user.username }}
    <br>
    <strong>User Email:</strong>{{ profile.user.email }}
    <br>
    <!-- first name -->
    <strong>First Name:</strong>{{ profile.first_name }}
    <br>
    <!-- last name -->
    <strong>Last Name:</strong>{{ profile.last_name }}
    <br>
    <!-- profile picture -->
    <strong>Profile Picture:</strong><img src="{% if profile.picture %}{{ profile.picture.url }}{% else %}https://zipmex.com/static/d1af016df3c4adadee8d863e54e82331/1bbe7/Twitter-NFT-profile.jpg{% endif %}" alt="Profile Picture" height="100" >
    <br>
    <!-- bio -->
    <strong>Bio:</strong>{{ profile.bio }}
{% endblock %}

demo/authentication/templates/authentication/reg.html
{%  extends 'authentication/base.html' %}
{% block Title %}Registration{% endblock %}
{% block Body %}
    <form method="post" action="">
        <fieldset>
            <legend>Register</legend>
            {% csrf_token %}
            {% if form.errors %}
                <p style="color: orangered">Got errors! {{ form.errors }}</p>
            {% endif %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <p>{{ form.username }} {{ form.username.label }}</p>
            <p>{{ form.email }} {{ form.email.label }}</p>
            <p>{{ form.password1 }} {{ form.password1.label }}</p>
            <p>{{ form.password2 }} {{ form.password2.label }}</p>
            <input type="submit" value="Register">
        </fieldset>
    </form>
{% endblock %}

demo/authentication/templates/authentication/reset_password_complete.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset{% endblock %}
{% block Body %}
    <div class="content h-auto" style="margin-top: auto">
        <div class="container-fluid h-auto">
            <div class="row h-auto">
                <div class="col-md-8 col-md-offset-2" style="margin: auto;">
                    <div class="card">
                        <div class="header text-center">
                            <h4 class="title">Password Reset Complete</h4>
                            <p class="category">
                                Your password has been reset.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

demo/authentication/templates/authentication/reset_password_done.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset Done{% endblock %}
{% block Body %}
    <form method="post" class="container">
        <fieldset>
            <legend>Enter new password</legend>
            <span>Please enter your new password twice so we can verify you typed it in correctly.</span>
            <br>
            {% csrf_token %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <fieldset class="module aligned">
                <input class="hidden" autocomplete="username" value="rand4" hidden>
                <div class="form-row field-password1">
                    <label for="id_new_password1">New password:</label>
                    <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1">
                </div>
                <div class="form-row field-password2">
                    <label for="id_new_password2">Confirm password:</label>
                    <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2">
                </div>
                <input type="submit" class="btn btn-primary" value="Change my password">
            </fieldset>
        </fieldset>
    </form>
{% endblock %}

demo/authentication/templates/authentication/reset_password_sent.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset{% endblock %}
{% block Body %}
    <div class="content h-auto" style="margin-top: auto">
        <div class="container-fluid h-auto">
            <div class="row h-auto">
                <div class="col-md-8 col-md-offset-2" style="margin: auto;">
                    <div class="card">
                        <div class="header text-center">
                            <h4 class="title">Password Reset Sent</h4>
                            <p class="category">
                                We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
                            </p>
                            <p class="category">
                                If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

demo/authentication/templates/authentication/users.html
{% extends 'polls/base.html' %}
{% block Title %}Users{% endblock %}
{% block Body %}
    {% if user_list %}
        <ul>
            {% for profile in user_list %}
                <li>{{ profile.user.username }}<a href="{{ profile.get_absolute_url }}">Open</a> </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}